name: Testing CI

on:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

      - name: Connect and Deploy
        run: |
          ssh -i ~/.ssh/ec2-key.pem \
              -o StrictHostKeyChecking=no \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
              "
              if [ -d "~/apps/testing-deploy/.git" ]; then
                echo "Exists"
                cd ~/apps/testing-deploy && git pull
              else
                echo "Not found"
                mkdir -p ~/apps && git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rashid-ameer/github-workflow-testing.git ~/apps/testing-deploy
              fi
              cd ~/apps/testing-deploy && npm ci && npm run build && (pm2 restart 'testing-deploy' || pm2 start npm --name 'testing-deploy' -- start)
              "
